### ISSUE TITLE
[29-34] Build login process

### ISSUE THREAD

**Issue by oluengob** [TheTributeCommunity/fesbal-frontend#12]
# Description
When user presses "Iniciar sesión" it leads him/her to login screen (number 29). User needs to enter both the ID number and the the password in order to access the app.

In the first access the password is the one sent  after finishing the onboarding process. In case the user can't find it or don't remember it, he/she can click on "I forgot my password". clicking on this links leads the user to introduce his/her email account to get a new password in their email. 

# Definition of Done
- Button is disabled until inputs are filled
- "¿Olvidaste contraseña?" leads to screen 32
-In case that the ID document (user) or the password is wrong it shows an error (see wireframe below - Error screen)
- In password recovery, "enviar email" button is disabled until valid email format is entered.
- "Ir a inicio de sesión" button leads to screen 29.
- Screen follows provided designs

# Design wireframes
- Before entering data: [link](https://www.figma.com/file/9dl1pcE6HzqCZOTXkGJBk6/Version-0.4---FESBAL?node-id=108%3A2258&t=LEBYLZX0eHGJoGBT-4)
- After entering data: [link](https://www.figma.com/file/9dl1pcE6HzqCZOTXkGJBk6/Version-0.4---FESBAL?node-id=409%3A5273&t=LEBYLZX0eHGJoGBT-4)
- Error screen: [link](https://www.figma.com/file/9dl1pcE6HzqCZOTXkGJBk6/Version-0.4---FESBAL?node-id=417%3A5324&t=LEBYLZX0eHGJoGBT-4)
- Password recovery [link](https://www.figma.com/file/9dl1pcE6HzqCZOTXkGJBk6/Version-0.4---FESBAL?node-id=971%3A11555&t=VSpoJoO9elaP5zRZ-4)

# Guidelines
- Try to use the dependencies already in the project. You can add new ones, if it’s needed to implement the feature
- Keep in mind that this is a front end test, it is not required to store the data on a backend
- We are open to suggestions and questions. If you are not sure about something, go ahead and ask it!

**Comment by nayarardgz** [comment]
Closing this issue to break it into smaller parts
