### ISSUE TITLE
[3-4] Build data inputs for user to enter name and last name to complete onboarding step

### ISSUE THREAD

**Issue by oluengob** [TheTributeCommunity/fesbal-frontend#4]
* **Technologies**: React, Typescript.
* **Difficulty of the issue**: Advance, Medium, Beginners
* **Topics**: 

# Description
Build screen with data inputs: Name & last name button is disabled until data in both inputs is entered

# Definition of Done
- Both inputs are text only
- “Continuar” (“Continue”) button is disabled until inputs are completed
- Screen follows provided designs

# Design wireframes

- Without focus: [link](https://www.figma.com/file/eaAfUatNrDWpFPbkCsLMYG/Frontend-contribution---Onboarding-process?node-id=1%3A1633)
- With focus: [link](https://www.figma.com/file/eaAfUatNrDWpFPbkCsLMYG/Frontend-contribution---Onboarding-process?node-id=1%3A1648)
- Input completed: [link](https://www.figma.com/file/eaAfUatNrDWpFPbkCsLMYG/Frontend-contribution---Onboarding-process?node-id=1%3A1751)

# Guidelines
- Try to use the dependencies already in the project. You can add new ones, if it’s needed to implement the feature
- Keep in mind that this is a front end test, it is not required to store the data on a backend
- We are open to suggestions and questions. If you are not sure about something, go ahead and ask it!

**Comment by aufgfua** [comment]
@oluengob [PR](https://github.com/TheTributeCommunity/fesbal-frontend/pull/60) approved and merged. 
Can I close this issue? Or do you plan to verify and close them one by one in the future, for organization purposes?
