### ISSUE TITLE
[5-6] Build birth date selector for user to complete onboarding step.

### ISSUE THREAD

**Issue by oluengob** [TheTributeCommunity/fesbal-frontend#5]
* **Technologies**: React, Typescript.
* **Difficulty of the issue**: Advance, Medium, Beginners
* **Topics**: 

# Description
Build screen with date selector. Button is disabled until the birth date is selected.

# Definition of Done
- Time format must be Day / Month / Year
- Date selected is smaller than the current date
- There should be a date validation where user must have more than 18 years old
- Screen follows provided designs

# Design wireframes

Without focus: [link](https://www.figma.com/file/eaAfUatNrDWpFPbkCsLMYG/Frontend-contribution---Onboarding-process?node-id=1%3A2200)
With focus: [link](https://www.figma.com/file/eaAfUatNrDWpFPbkCsLMYG/Frontend-contribution---Onboarding-process?node-id=1%3A2214)

# Guidelines
- Try to use the dependencies already in the project. You can add new ones, if it’s needed to implement the feature
- Keep in mind that this is a front end test, it is not required to store the data on a backend
- We are open to suggestions and questions. If you are not sure about something, go ahead and ask it!

**Comment by aufgfua** [comment]
It looks like someone already did this task, so I stopped it.
If it isn't the case, let me know because I have it like 70% finished
